sudo: required
services:
    - docker

before-install:
    - docker build -t akhileshojha/passworddocker -f ./password-validator/Dockerfile.dev ./password-validator

script:
    - docker run -e CI=true akhileshojha/passworddocker npm test

after_success:
    - docker build -t akhileshojha/dock-password-validator ./password-validator
    - docker build -t akhileshojha/dock-password-server ./password-server
    - docker build -t akhileshojha/dock-nginx ./nginx

    #Add docker pass and userid from travis to cli

    - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERID" --password-stdin

    #push image in docker hub
    - docker push akhileshojha/dock-password-validator
    - docker push akhileshojha/dock-password-server
    - docker push akhileshojha/dock-nginx
